---
- name: Deploy HMIS Microservices
  hosts: all
  become: yes
  vars:
    docker_compose_version: "v2.27.0"

  tasks:
    - name: Update apt packages
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required system packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
        state: present

    - name: Create directory for Docker GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker's official GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        force: true

    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    - name: Install Docker Engine and plugins
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Create the hmis project directory
      ansible.builtin.file:
        path: /opt/hmis
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy docker-compose.yml and .env file
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "/opt/hmis/{{ item.dest }}"
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      loop:
        - { src: './docker-compose.yml', dest: 'docker-compose.yml' }
        - { src: './.env', dest: '.env' }

    - name: Log in to the Docker registry
      community.docker.docker_login:
        username: "{{ docker_registry_username }}"
        password: "{{ docker_registry_password }}"
      no_log: true

    - name: Deploy or update the Docker Compose stack
      community.docker.docker_compose_v2:
        project_src: /opt/hmis
        pull: true
      environment:
        - DOCKER_TAG={{ docker_tag | default('latest') }}
        - DOCKER_USERNAME={{ docker_registry_username }}

